### ISSUE TITLE
Should we change the base font family to Avenir?

### ISSUE THREAD

**Issue by himedlooff** [cfpb/cf-core#22]
Seems like almost everything is in Avenir except longer blocks of text. It might make things easier on the front end if we just used that as the default font family instead of Georgia. Any thoughts?

**Comment by Scotchester** [comment]
I think we should bite the bullet and do this. It will help me immediately in the link styling refactor work.

**Comment by himedlooff** [comment]
Let's get some more feedback: @ascott1, @contolini, @mistergone, @virginiacc

**Comment by mistergone** [comment]
It is the intention of the "cascading" part of CSS to make life easier, so if it makes things easier, then I'd go with it.

The only possible objection I have is that "long text blocks" would be what I'd consider "the default," possibly earning "the default font," whereas headers and such would be considered "modified from the default," but that sounds suspiciously like an argument for "semantic" CSS... and I think CSS is just a tool, not a semantic markup. :dancer: :dancer: :rocket:

**Comment by contolini** [comment]
Will this change negatively impact non-CFPB projects using CF?

**Comment by Scotchester** [comment]
@mistergone That was my exact thought process in originally pushing for Georgia to be the default, but I can no longer ignore the pragmatic cascade issues it continues to create :)

@contolini I don't think it would. Did you have any specific reasons it might?

**Comment by contolini** [comment]
Nah just curious.

**Comment by virginiacc** [comment]
My one concern about this would also be about external users -- we could use semantic font variables to make it easier to customize.

**Comment by Scotchester** [comment]
I agree about the value of adding variables. As we noted during the chat we had this afternoon, we definitely need to take several steps to make this easier for third parties to use. In the meantime, I vote for moving forward with this change to make our internal lives easier.

**Comment by himedlooff** [comment]
Do we have a proposed way for adding Georgia when we need it? Maybe with a `.serif` class? I'd be all in favor of a `.long-read` class that adds Georgia to all paragraph and list elements as well as forcing underlines on links within those same elements. This would also make non underlined links the default which I think would make a lot of things easier as well.

**Comment by Scotchester** [comment]
My first thought was to do:

``` css
article p,
article li,
article dd {
    font-family: Georgia, "Times New Roman", serif;
}
```

and see if that hits most of the use cases. But I like the `.long-read` proposal, too.

**Comment by mistergone** [comment]
I generally support classes instead of overwriting HTML elements, but fonts and underlined links aren't my fears when it comes to that. I'm cool with either solution.

:heavy_plus_sign::heavy_plus_sign: on adding variables.

**Comment by Scotchester** [comment]
This issues is missing some of the context that I commented on here: https://github.com/cfpb/cfgov-refresh/pull/686#discussion_r33583147 So here it is:

The problem is this: We want paragraphs of body copy of substantial length—length of the whole section of copy, not length of an individual paragraph—to be set in Georgia. Pretty much all other paragraphs are fair game for Avenir.

Back when we started CF, we thought that paragraphs of body copy were the "default" case, and as such, set that as the base font family, overriding with Avenir Next when necessary. This led to the case of the not-very-semantic class `.short-desc`, among other unfortunate things like `.styled-link` and `.micro-copy`. (See: [cf-typography docs](https://cfpb.github.io/cf-typography/docs/).)

Since then, we've definitely had second thoughts about reversing our position on what the base font family should be. What do you all think about changing the base font family to Avenir Next (i.e., the sans-serif stack), and creating a new rule that sets "long-read" body copy in Georgia? (serif stack).

**Comment by jimmynotjim** [comment]
I'm actually in favor of setting the reading text as the default (so keeping Georgia) and changing to the alt as necessary. I just think we need a better name for it so it's clear what's being changed and why.

Edit: I'm also proposing the newly named class only change the font-family, so we could have something like `.alt-font` and `.alt-font__med` in the html, rather than trying to set the fonts all over the place in the styles. This will reduce a lot of duplicated font declarations as well.

**Comment by himedlooff** [comment]
It also doesn't help that there are many many different typographic design treatments.
